### ISSUE TITLE
Tool doesn't terminate

### ISSUE THREAD

**Issue by wires** [aaronland/webster-cli#3]
Hi, thanks for publishing this, it's exactly what I need. However, after building, the tool runs (e.g. `-h`), but when passed a HTML file and target PDF it doesn't terminate.

```
wires@zzz ~/P/webster-cli> swift run webster-cli index.html bla.pdf
^C⏎
```

How can I debug this? Here is some initial version info:

```
wires@zzz ~/P/webster-cli> swift -v
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.6.0
/Applications/Xcode.app/Contents/Developer/usr/bin/lldb "--repl=-enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -color-diagnostics"
Welcome to Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53).
```

Thanks

**Comment by wires** [comment]
My bad, after looking at the sources, I figured the problem had to do with the arguments. After supplying `file://` URLs with full paths it worked as charm. 

E.g.:

```
./.build/debug/webster-cli \
  file:///Users/wires/PrintSourceCode/webster-cli/index.html \
  file:///Users/wires/PrintSourceCode/webster-cli/bla.pdf
```

Thanks ❤️ great tool & great timing (for me) to release this!

**Comment by thisisaaronland** [comment]
Thanks. I will investigate why the code doesn't work with scheme-less paths, because it's supposed to:

https://github.com/aaronland/webster-cli/blob/master/Sources/webster-cli/main.swift#L35-L44

**Comment by thisisaaronland** [comment]
Oh, I see - there is support for scheme-less target URIs but not source URIs.

**Comment by wires** [comment]
Nice thanks! About to print a whole pile of source code with this, *yay* dead trees
